---
#__Необходимо запускать с ключем -K (ansible-playbook python_install.yml -K)

#############################################################
# OperatingSystem : CentOS 8 server
# Hostname : masterdns.zsmdevops.ru
# IP Address : 192.168.56.103/24
#############################################################
- name: Install DNS and other APPs - Apache, mc, ntpdate ......
  hosts: Mail2
  become: yes

  tasks:

 
  #_____________Block for RedHat (with "yum" package manager)__________
  - block:

      - name: Download and Extract PostfixAdmin
        unarchive:
          src: https://sourceforge.net/projects/postfixadmin/files/postfixadmin/postfixadmin-3.2/postfixadmin-3.2.tar.gz
          dest: /var/www/html/padmin
          owner: apache
          group: apache
          remote_src: yes
          extra_opts: [--strip-components=1]





#Skopirovat' fayly nastroek na svoi mesta
#      - name: Copy named.conf
#        copy: src=/home/zsm/ansible/files/named.conf dest=/etc owner=root group=named mode=0640

#      - name: Copy forward.zsmdevops, reverse.zsmdevops
#        copy: src=/home/zsm/ansible/files/{{ item }} dest=/var/named owner=root group=named mode=0644
#        loop:
#          - "forward.zsmdevops"
#          - "reverse.zsmdevops"

#Start and add to autorun service named (DNS server)
#      - name: Start and add to autorun service named (DNS server)
#        systemd:
#          state: started
#          enabled: yes
#          name: named

#Razreshit' DNS-serveru ispolzovat' porty 53 v Firewalld


#Zamena DNS servera na nash
#(Dodelat',chtob zamenyalo DNS,esli on est', i dobavlyalo, esli net
#      - name: Add our DNS
#        lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-enp0s8 regexp=^DNS1= line=DNS1="192.168.56.108"

#Dobavlenie IP DNS servera v resolv.conf
#      - name: add DNS server's IP at /etc/resolv.conf
#        lineinfile: dest=/etc/resolv.conf
#          regexp=''
#          insertafter=EOF
#          line='nameserver 192.168.56.107'


#        service: name=httpd state=started enabled=yes

    when: ansible_pkg_mgr!="apt"

