---
#__Необходимо запускать с ключем -K (ansible-playbook python_install.yml -K)
- name: All info
  hosts: AWS
  become: yes
#  become_user: zsm
#  remote_user: zsm
#  gather_facts: false


  tasks:
#__Вывод на экрана результата команды setup (всей информации по хосту)
  - name: Info
    setup:
    register: var_setup
  - debug:
      var: var_setup
