---
#__Необходимо запускать с ключем -k -K (ansible-playbook python_install.yml -k -K)
- name: Python install
  hosts: DNS
  become: yes
#  become_user: zsm
  remote_user: root
  gather_facts: false


  tasks:

#  - name: Check for Python
#    raw: test -e /usr/bin/python
#    #__Отключить проверку на changed#
#    changed_when: false  
#    #__Отключить проверку на failed#
#    failed_when: false
#    register: check_python
#    failed_when: check_python.rc == 0
#  - debug:
#      var: check_python
 
  - name: Install Python via YUM or APT
#Esli padaet v error, udalit' "apt -y update"
    raw: test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal) || (yum -y install python3)
#    when: check_python.rc!=0
