---
- name: Copy Files or Directories
  hosts: Mail2
  become_user: root
  become: yes


  vars:
    copy_from: /home/zsm/ansible
    copy_to: /home/zsm/Copy_From_Ubuntu

  tasks:
  - name: Copy files or directories 
    copy: src=/var/www/html/padmin/config.inc.php dest=/var/www/html/padmin/config.local.php owner=apache group=apache mode=0664 remote_src=yes

#  - name: Copy files or directories
#    copy: src=/home/zsm/ansible/files/{{ item }} dest=/var/named owner=root group=named mode=0644
#    loop:
#      - "forward.zsmdevops"
#      - "reverse.zsmdevops"

  
