---
- name: Install and Copy Web Server with Roles
  hosts: all
  become: yes

  roles:
    - { role: deploy_apache_web, when: ansible_system == 'Linux' }
#    - deploy_apache_web
#    - role2
#    - role3
#    - .....
